<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="chassi_length" value="0.5"/>
    <xacro:property name="chassi_width" value="0.13"/>
    <xacro:property name="chassi_height" value="0.06"/>

    <xacro:property name="chassi_top_length" value="0.5"/>
    <xacro:property name="chassi_top_width" value="0.23"/>
    <xacro:property name="chassi_top_height" value="0.04"/>

    <xacro:property name="wheel_radius" value="0.035"/>
    <xacro:property name="wheel_length" value="0.028"/>

    <!-- Links-->
    <link name="base_footprint"/>

    <!-- Chassis Aufbau-->

    <link name="chassis">
        <visual>
            <origin xyz="0.0 0.0 ${chassi_height/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassi_length} ${chassi_width} ${chassi_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 ${chassi_height/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassi_length} ${chassi_width} ${chassi_height}"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="3.0" l="${chassi_length}" w="${chassi_width}" h="${chassi_height}"
                           xyz="0.0 0.0 ${chassi_height/2}" rpy="0 0 0"/> 
    </link>
    <gazebo reference="chassis">
        <material>Gazebo/Grass</material>
    </gazebo>

    <link name="chassis_top">
        <visual>
            <origin xyz="0.0 0.0 ${chassi_top_height/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassi_top_length} ${chassi_top_width} ${chassi_top_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
        <collision>
            <origin xyz="0.0 0.0 ${chassi_top_height/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassi_top_length} ${chassi_top_width} ${chassi_top_height}"/>
            </geometry>
        </collision>
        <xacro:box_inertia m="1.0" l="${chassi_top_length}" w="${chassi_top_width}" h="${chassi_top_height}"
                           xyz="0.0 0.0 ${chassi_top_height/2}" rpy="0 ${pi/2} 0"/> 
    </link>
    <gazebo reference="chassis_top">
        <material>Gazebo/Grass</material>
    </gazebo>


    <!-- WHEELS-->

    <xacro:macro name="wheel_link" params="prefix ">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="0.3" r="${wheel_radius/2}" h="${wheel_length/2}"
                           xyz="0 0 0" rpy="${pi/2} 0 0"/>                        
        </link>
        <gazebo reference="${prefix}_wheel">
            <material>Gazebo/Grey</material>
          <!--  <mu1 value="0.1"/> 
            <mu2 value="0.1"/>-->
             
            <mu1>100000000000000.0</mu1>
            <mu2>100000000000000.0</mu2>
            <kp>1000000000000.0</kp>
            <kd>10.0</kd>
            <minDepth>0.001</minDepth>
            <maxVel>0.1</maxVel>
            <fdir1>1 0 0</fdir1> 
        </gazebo>
    </xacro:macro>

    <xacro:wheel_link prefix="right"/>    
    <xacro:wheel_link prefix="left"/>
    
     

    <xacro:macro name="caster_wheel_link" params="prefix ">
        <link name="${prefix}_caster_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="white"/>
            </visual>
            <collision>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <sphere radius="${wheel_radius}"/>
                </geometry>
            </collision>
            <xacro:cylinder_inertia m="0.3" r="${wheel_radius/2}" h="${wheel_length/2}"
                           xyz="0 0 0" rpy="${pi/2} 0 0"/>                        
        </link>
        <gazebo reference="${prefix}_caster_wheel">
            <material>Gazebo/Grey</material>
            <mu1>0.01</mu1>
            <mu2>0.01</mu2>
            <kp>1000000.0</kp>
            <kd>100.0</kd>
            <minDepth>0.001</minDepth>
            <maxVel>0.1</maxVel> 
        </gazebo>
    </xacro:macro>

    <xacro:caster_wheel_link prefix="left_f"/>
    <xacro:caster_wheel_link prefix="left_r"/>  
    <xacro:caster_wheel_link prefix="right_f"/> 
    <xacro:caster_wheel_link prefix="right_r"/>
    
    <!-- Joints Fixed -->
    
    <joint name="base_link" type="fixed">
        <parent link="base_footprint"/>
        <child link="chassis"/>
        <origin xyz="0.0 0.0 ${wheel_radius}" rpy="0.0 0.0 0.0"/>
    </joint>

    <joint name="chassieAufbau" type="fixed">
        <parent link="chassis"/>
        <child link="chassis_top"/>
        <origin xyz="0.0 0.0 ${chassi_height}" rpy="0.0 0.0 0.0"/>
    </joint>

    <!-- Joints Moving-->

    <joint name="joint_1" type="continuous">
        <parent link="chassis"/>
        <child link="right_wheel"/>
        <axis xyz="0 1 0"/>
        <origin xyz="0 -${chassi_width/2 + wheel_length/2 + 0.005} 0" rpy="0 0 0"/>
    </joint>

    <joint name="joint_2" type="continuous">
        <parent link="chassis"/>
        <child link="left_wheel"/>
        <axis xyz="0 1 0"/>
        <origin xyz="0 ${chassi_width/2+ wheel_length/2 + 0.005} 0" rpy="0 0 0"/>
    </joint>
     
    <joint name="joint_rf" type="continuous">
        <parent link="chassis"/>
        <child link="right_f_caster_wheel"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${chassi_length/3} -${chassi_width/2 + wheel_length/2 + 0.005} 0" rpy="0 0 0"/>
        <mimic joint="joint_1" multiplier="1"/>
    </joint>

    <joint name="joint_rr" type="continuous">
        <parent link="chassis"/>
        <child link="right_r_caster_wheel"/>
        <axis xyz="0 1 0"/>
        <origin xyz="-${chassi_length/3} -${chassi_width/2 + wheel_length/2 + 0.005} 0" rpy="0 0 0"/>
        <mimic joint="joint_1" multiplier="1"/>
    </joint>

    <joint name="joint_lf" type="continuous">
        <parent link="chassis"/>
        <child link="left_f_caster_wheel"/>
        <axis xyz="0 1 0"/>
        <origin xyz="${chassi_length/3} ${chassi_width/2 + wheel_length/2 + 0.005} 0" rpy="0 0 0"/>
        <mimic joint="joint_2" multiplier="1"/>
    </joint>

    <joint name="joint_lr" type="continuous">
        <parent link="chassis"/>
        <child link="left_r_caster_wheel"/>
        <axis xyz="0 1 0"/>
        <origin xyz="-${chassi_length/3} ${chassi_width/2 + wheel_length/2 + 0.005} 0" rpy="0 0 0"/>
        <mimic joint="joint_2" multiplier="1"/>
    </joint>


</robot>