joy_teleop_:
  ros__parameters:
    turm: 
      type: topic
      interface_type: geometry_msgs/msg/TwistStamped
      topic_name: turret_controller/cmd_vel
      #topic_name: turm_controller/cmd_vel

      deadman_buttons: [5]

      axis_mappings:
        twist-linear-x:
          axis: 4
          scale: 1.0
          offset: 0.0
        twist-angular-z:
          axis: 3
          scale: 1.0
          offset: 0.0