controller_manager:
  ros__parameters:
    update_rate: 10 # Hz
    # use_sim_time: true

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    tank_speed_controller:
      type: velocity_controllers/JointGroupVelocityController

    turret_controller:
      type:  joint_trajectory_controller/JointTrajectoryController # forward_command_controller/ForwardCommandController # 

    pipe_controller:
      type: joint_trajectory_controller/JointTrajectoryController # forward_command_controller/ForwardCommandController #


    chassis_controller:
      type: diff_drive_controller/DiffDriveController

    turm_controller:
      type: diff_drive_controller/DiffDriveController

    turret_position_controller:
      type: position_controller/JointGroupsPositionController

    
turret_position_controller:
  ros__parameters:
    joints:
      - joint_3


tank_speed_controller:
  ros__parameters:
    joints:
      - joint_1
      - joint_2
      

turret_controller:
  ros__parameters:
    joints:
      - joint_3

    #interface_name: position
      

    command_interfaces:
      - velocity

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true

pipe_controller:
  ros__parameters:
    joints:
      - joint_4

    command_interfaces:
      - velocity

    state_interfaces:
      - position

    open_loop_control: true
    allow_integration_in_goal_trajectories: true




chassis_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: true
    left_wheel_names: ['joint_2']
    right_wheel_names: ['joint_1']
    publish_rate: 50.0
    pose_covariance_diagonal: [0.001, 0.001, 1.0e-3 ,1.0e-3, 0.01]
    twist_convariace_diagonal: [0.001, 0.001, 1.0e-3 ,1.0e-3, 0.01]

    wheel_radius: 0.033
    wheel_separation: 0.163
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    wheel_separation_multiplier: 1.0

    cmd_vel_timeout: 0.25
    base_frame_id: base_footprint
    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 1.0
        min_velocity: -0.5
        has_acceleration_limitis: true
        max_acceleration: 0.8
        min_acceleration: -0.4
        has_jerk_limits: false

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 1.7
        min_velocity: -1.7
        has_acceleration_limitis: true
        max_acceleration: 1.5
        min_acceleration: -1.5
        has_jerk_limits: false

turm_controller:
  ros__parameters:
    type: diff_drive_controller/DiffDriveController
    use_stamped_vel: true
    left_wheel_names: ['joint_3']
    right_wheel_names: ['joint_4']
    publish_rate: 50.0
    #pose_covariance_diagonal: [0.001, 0.001, 1.0e-3 ,1.0e-3, 0.01]
    #twist_convariace_diagonal: [0.001, 0.001, 1.0e-3 ,1.0e-3, 0.01]

    wheel_radius: 0.06
    wheel_separation: 0.163
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0
    wheel_separation_multiplier: 1.0

    cmd_vel_timeout: 0.25
    base_frame_id: base_footprint
    publish_limited_velocity: true
    publish_wheel_data: true
    enable_odom_tf: true

    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.2
        min_velocity: -0.2
        has_acceleration_limitis: true
        max_acceleration: 0.4
        min_acceleration: -0.2
        has_jerk_limits: false

    angular:
      z:
        has_velocity_limits: true
        max_velocity: 0.5
        min_velocity: -0.5
        has_acceleration_limitis: true
        max_acceleration: 0.3
        min_acceleration: -0.3
        has_jerk_limits: false