<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">
    
    <xacro:property name="chassi_length" value="0.5"/>
    <xacro:property name="chassi_width" value="0.13"/>
    <xacro:property name="chassi_height" value="0.06"/>

    <xacro:property name="chassi_top_length" value="0.5"/>
    <xacro:property name="chassi_top_width" value="0.23"/>
    <xacro:property name="chassi_top_height" value="0.04"/>

    <xacro:property name="wheel_radius" value="0.035"/>
    <xacro:property name="wheel_length" value="0.028"/>

    <!-- Links-->
    <link name="base_footprint"/>

    <!-- Chassis Aufbau-->

    <link name="chassis">
        <visual>
            <origin xyz="0.0 0.0 ${chassi_height/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassi_length} ${chassi_width} ${chassi_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>

    <link name="chassis_top">
        <visual>
            <origin xyz="0.0 0.0 ${chassi_top_height/2}" rpy="0.0 0.0 0.0"/>
            <geometry>
                <box size="${chassi_top_length} ${chassi_top_width} ${chassi_top_height}"/>
            </geometry>
            <material name="black"/>
        </visual>
    </link>


    <!-- WHEELS-->

    <xacro:macro name="wheel_link" params="prefix ">
        <link name="${prefix}_wheel">
            <visual>
                <origin xyz="0.0 0.0 0.0" rpy="${pi/2} 0.0 0.0"/>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_length}"/>
                </geometry>
                <material name="white"/>
            </visual>
        </link>
    </xacro:macro>

    <xacro:wheel_link prefix="right"/>
    <xacro:wheel_link prefix="left"/>

    <xacro:wheel_link prefix="right_f"/> 
    <xacro:wheel_link prefix="right_r"/> 
    <xacro:wheel_link prefix="left_f"/>
    <xacro:wheel_link prefix="left_r"/>  

</robot>